export default [
	{ _id: 'GYTfPF37t5jFRGjsT', name: 'Analysis' },
	{ _id: 'S2fC5XZvGoa674R2L', name: 'BSME' },
	{ _id: 'Tpu4zfMXKeRJvZmyv', name: 'Building' },
	{ _id: 'LmhA55egqh2FynsoN', name: 'CAD' },
	{ _id: 'NbzWGyZzGXEDXKbSq', name: 'Design' },
	{ _id: 'WKbunEJkK2L7XLuoN', name: 'Engineering' },
	{ _id: 'tjrSphKDNoj2QsRDX', name: 'Electrical' },
	{ _id: 'i79X55RPDzAX6Q5ZA', name: 'Drawings' },
	{ _id: 'JxsJ8As2tDNg8ymJa', name: 'Equipment' },
	{ _id: 'qviM2WzSvHs3yJuiq', name: 'Manufacturing' },
	{ _id: 'GbHeEmNhQpK4P4c9T', name: 'Mechanical' },
	{ _id: 'XvyTbDMRsL99ZL8JG', name: 'Product' },
	{ _id: 'niuB8Q2SxAhEYMMbh', name: 'Performance' },
	{ _id: 'KAXTqsC7BSSh3Z6kq', name: 'Systems' },
	{ _id: 'g6aovwoQXsc9ao7Rh', name: 'Team' },
	{ _id: 'piZNSPRmZCkvrpgsp', name: 'Testing' },
	{ _id: 'HmjBiCeFQHBTLv288', name: 'Technical' },
	{ _id: 'Q5CByEukyuJ9wGzcJ', name: 'healthcare' },
	{ _id: 'CtxCbqmdDGxe7MQSj', name: 'care' },
	{ _id: 'sQ3MJiM3T2RG4534k', name: 'health' },
	{ _id: 'dxSw4seo6uYZxgNFK', name: 'selfless' },
	{ _id: 'm5Qk2fwp4SakAoZPS', name: 'icu' },
	{ _id: '2DSTTHwDqagFfrzb5', name: 'Coaching' },
	{ _id: 'wiuYj2sDhCdh9fowd', name: 'Communication' },
	{ _id: 'HAtLhaE7LMuitKhtz', name: 'Collaboration' },
	{ _id: '6XCK4ExFu5SQnooxu', name: 'Directing' },
	{ _id: 'DatpZESJDHsb9Ncik', name: 'Creating Assignments' },
	{ _id: 'BS3dp8mkEzbzbR56L', name: 'Development' },
	{ _id: 'gpQyzkgxef2YvrWTY', name: 'HVAC' },
	{ _id: 'SX4q54ajttKE8bgmD', name: 'SolidWorks' },
	{ _id: 'xMt38J8rSC3Lwohtg', name: 'Clinical' },
	{ _id: 'vPs3Gqgwsf2AoTz9Y', name: 'certifications' },
	{ _id: '4YpiADrKg8STJwTA7', name: 'Childcare' }
];
